# Precomputed_annotation_downsampling_debug

The purpose of this notebook is to figure out how to multiple spatial indexes for a precomputed annotation layer and to determine when they are needed for performance in terms of number of annotations. Refer to this document: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md for the general structure of these precomputed annotation layers and in particular the section: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#spatial-index for spatial indexing.

So far, I have been able to successfully create a precomputed annotation layer with only a single spatial index, `spatial0`. This works well for up to a 10^5 annotations, but once you get above that the load time  starts to suffer. To get faster load times, spatial indexing is recommended, similar to downsampling for image and segmentation layers. To compute the spatial indexes, the instructions are:

- For each grid position cell at the coarsest level, compute the set remaining_annotations(0, cell) of annotations that intersect the cell. Note that a single annotation may intersect multiple cells.

- Sequentially generate spatial index level, starting at level=0 (the coarsest level):

- Define maxCount(level) to be the maximum over all cell positions of the size of remaining_annotations(level, cell).
- For each cell:
    - Compute a subset emitted(level, cell) of remaining_annotations(0, cell) where each annotation is chosen uniformly at random with probability min(1, limit / maxCount(level)).
    - This spatial index level maps cell to the list of annotations in emitted(level, cell). The annotations are encoded in the multiple annotation encoding also used by the related object id index; the list should be ordered randomly.
    - For each child_cell in level level+1 contained within cell: Compute the set remaining_annotations(level+1, child_cell) of annotations within remaining_annotations(level, cell) - emitted(level, cell) that intersect child_cell.
- Continue generating successively finer spatial index levels until no annotations remain.


To run this we will need to set the variable `limit`. It determines the subsampling level. Let's set it to 10000 for our example. We also need to know our total number of cells, which is 1388798 for an5 in Jess' 201904_ymaze_cfos cohort. We also need to decide the order in which to save the subset of cells in each grid cell file in each spatialX/ folder. The instruction say to use bit-reserved morton code, which I have no idea what that means. This section of the document says to order them randomly: https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/annotations.md#multiple-annotation-encoding, so I'm going to try that. We also need to pre-decide how we are going to chunk up the volume. The instructions say to chunk it up in a way that results in the most isotropic chunk sizes. This is similar to how we would do things for downsampling. In our case here, we have an initial volume size of 2160, 2560, 687. So level1 will have grid_shape = [2,2,1] and a chunk size of [1080,1280,687]. level2 will have a grid shape of [4,4,1] and a chunk size of [540,640,687]. Then since this is close to isotropic the remaining grid shapes will increase by factors of 2 in each dimension , so [8,8,2], ... and chunk sizes will just be divided by 2 in each dimension, so [270,320,343.5], .... This is repeated until there no annotations remain - what does that mean?

Since our coarsest level has grid_shape = [1,1,1] then the set of `remaining_annotations(0, cell)` that intersect the cell is all of the annotations since we only have 1 cell. 

**level 0**
maxCount(level=0) = total cell count because we only have one 1 cell and it has all of the cells in it

There is only 1 cell, so we just have to:
- calculate the subset emitted(level=0,cell=0) of remaining_annotations(0, cell=0) where each annotation is chosen uniformly with probability min(1,limit=1000 / maxCount(level=0)) = 10000/1388798. Therefore, only ~0.7% of annotations will end up in this level.
- Save this subset to a file spatiall0/0_0_0 using the multiple annotation encoding that we normally use and in a random order. 
- For each child_cell (the four cells at level 1) contained within this cell, compute the set remaining_annotations(level=1,child_cell) of annotations within remaining_annotations(level=0,cell=0) - emitted(level=0,cell=0) that intersect child_cell. Since there are 4 child cells: [0,0,0],[1,0,0],[0,1,0],[1,1,0] and the current level is level0, remaining_annotations(level=0,cell=0) is all cells and emitted(level=0,cell=0) is the 0.7% that were saved out to spatial0/0_0_0. So of the 99.3% of the cells, figure out which of those intersect with each child cell. 

**level 1**
4 cells: [0,0,0],[1,0,0],[0,1,0],[1,1,0]
maxCount(level=1)) = max of remaining_annotations(level=1,cell_i) where at the end of the previous step we calculated all four of these remaining_annotations.

For each cell i of the 4 cells:
- calculate the subset emitted(level=1,cell=i) of remaining_annotations(level=1, cell=i) where each annotation is chosen uniformly with probability min(1,limit=1000 / maxCount(level=1)) = 10000/maxCount(level=1). 
- Save this subset to a file spatiall1/cell_i using the multiple annotation encoding that we normally use and in a random order.
- For each child_cell of this cell, compute the set remaining_annotations(level=2,child_cell) of annotations within remaining_annotations(level=1,cell=i) - emitted(level=1,cell=i) that intersect child_cell. Since there are 4 child cells: [0,0,0],[1,0,0],[0,1,0],[1,1,0] and the current level is level1, remaining_annotations(level=1,cell=i) was calculated in the previous step and emitted(level=1,cell=i) is the value we calculated just above that were saved out to spatial1/cell_i. So of the fraction of these of these cells, figure out which of those intersect with each child cell.

Do this until maxCount(level) is 0

In [17]:
import numpy as np
import os
import csv
import struct
import json
from cloudvolume import CloudVolume
import matplotlib.pyplot as plt
import neuroglancer
%matplotlib inline

In [18]:
# get the raw-space cells file and load it in
animal_id = 5
pth=os.path.join('/jukebox/wang/Jess/lightsheet_output',
        '201904_ymaze_cfos','processed',f'an{animal_id}','clearmap_cluster_output',
        'cells.npy')
converted_points = np.load(pth)

In [19]:
len(converted_points)

1388798

In [58]:
converted_points.shape

(1388798, 3)

In [197]:
unique_coordinates = np.unique(converted_points,axis=0)

In [200]:
len(unique_coordinates)

1388798

In [199]:
np.random.shuffle(unique_coordinates) # does it in place

In [201]:
def calculate_factors(level):
    # Calculate the factor to apply to the grid_shape/chunk size at a given spatial index level
    d = {}
    d[0] = [1,1,1]
    d[1] = [2,2,1]
    d[2] = [2,2,1]
    for i in range(3,20):
        d[i] = [2,2,2]
    return d[level]

In [202]:
# We need a function to calculate the subset emitted(level,cell,limit) 
def subset(level,cell,limit=10000):
    # Assumes two global dictionaries exist: remaining_annotations, maxCount
    rem = remaining_annotations[level][cell] # annotations 
    if maxCount[level] > limit:
        prob = limit/maxCount[level]
    else:
        N=maxCount[level]
    subset = np.random.choice(rem,size=N,replace=False) # uses a uniform distribution with no replacement
    return subset
    


In [203]:
def make_cells(grid_shape):
    # Make a list of cells ["0_0_0","1_0_0", ...] given a grid shape
    cells = []
    for x in range(grid_shape[0]):
        for y in range(grid_shape[1]):
            for z in range(grid_shape[2]):
                cell = f"{x}_{y}_{z}"
                cells.append(cell)
    return cells

In [204]:
def get_child_cells(cell,factor):
    # Given a cell string e.g. 1_2_3 and a factor, e.g. [2,2,1]
    # figure out all of the child cells 
    child_cells = []
    xcell,ycell,zcell = [int(x) for x in cell.split('_')] # n,m,p
    xfactor,yfactor,zfactor = factor # x,y,z
    for xf in range(0,xfactor):
        x_child = xcell*xfactor + xf
        for yf in range(0,yfactor):
            y_child = ycell*yfactor + yf
            for zf in range(0,zfactor):
                z_child = zcell*zfactor + zf
                child_cell = f"{x_child}_{y_child}_{z_child}"
                child_cells.append(child_cell)
    return child_cells

In [205]:
def save_cellfile(level,cell,coordinates):
    # We already know how to encode just the coordinates. Do it like so for the first 100 points
    spatial_dir = os.path.join(layer_dir,f"spatial{level}")
    if not os.path.exists(spatial_dir):
        os.mkdir(spatial_dir)
    filename = os.path.join(spatial_dir,cell)
    total_count = len(coordinates)
    with open(filename,'wb') as outfile:
        buf = struct.pack('<Q',total_count)
        pt_buf = b''.join(struct.pack('<3f',x,y,z) for (x,y,z) in coordinates)
        buf += pt_buf
        id_buf = struct.pack('<%sQ' % len(coordinates), *range(len(coordinates)))
        buf += id_buf
        outfile.write(buf)
    print(f"wrote {filename}")

In [280]:
def find_intersecting_coordinates(coord_array,lower_bounds,upper_bounds):
    # Of the coordinates in coord_list find the ones that are between lower_bounds and upper_bounds in x,y,z
    # return the indices of coord_array inside the bounds
    mask = (coord_array[:,0]>lower_bounds[0]) & (coord_array[:,0]<=upper_bounds[0]) & \
           (coord_array[:,1]>lower_bounds[1]) & (coord_array[:,1]<=upper_bounds[1]) & \
           (coord_array[:,2]>lower_bounds[2]) & (coord_array[:,2]<=upper_bounds[2])
    return coord_array[mask]


In [307]:
# initialize
layer_dir = "/home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex"
limit=10000

level=0
cell="0_0_0"
grid_shape = [1,1,1]
chunk_size = [2160,2560,687]
total_annotations = len(unique_coordinates)
remaining_annotations = {} # holds the array of coordinates in each cell at each level
remaining_annotations[level] = {cell:unique_coordinates}

maxCount = {}
while True:
# for level in range(0,3): # turn this into a while loop
    print("##############")
    print(f"Level: {level}")
    print("##############")
#     print("Remaining annotations at this level:")
#     print(remaining_annotations[level].values())
    N_annotations_this_level = [len(x) for x in remaining_annotations[level].values()]
    maxCount[level] = max(N_annotations_this_level)
    if maxCount[level] == 0:
        print("Finished!")
        break
    factor = calculate_factors(level)
    grid_shape = [a*b for a,b in zip(grid_shape,factor)]
    chunk_size = [a/b for a,b in zip(chunk_size,factor)]
    print(f"chunk_size={chunk_size}, maxCount = {maxCount[level]}")
    cells = make_cells(grid_shape)
    print("Have these cells:", cells)
    
#     print(cells)
    if maxCount[level] > limit:
        prob = limit/maxCount[level]
    else:
        prob = 1
    for cell in cells:
        print("In cell: ", cell)
        # Look up the remaining annotations in this cell, which was computed during the last iteration
        annotations_this_cell = remaining_annotations[level][cell]            
        N_annotations_this_cell = len(annotations_this_cell)
        print(f"started with {N_annotations_this_cell} annotations")
        next_factor = calculate_factors(level+1)
        child_cells = get_child_cells(cell,next_factor)
        next_chunk_size = [a/b for a,b in zip(chunk_size,next_factor)]

        if N_annotations_this_cell != 0:
            
            # Figure out the subset based on the probability we just calculated
            N_subset = int(round(N_annotations_this_cell*prob))
            # figure out list of indices of the remaining array to grab 
            subset_indices = np.random.choice(range(N_annotations_this_cell),size=N_subset,replace=False)
            print("annotations this cell:",annotations_this_cell[0:10])
            print("subset indices:",subset_indices[0:10])
            subset_cells = np.take(annotations_this_cell,subset_indices,axis=0)
            print(f"subsetted {len(subset_cells)} annotations")

            # save these cells to a file using the multi annotation convention we use for a single spatial index
            save_cellfile(level,cell,subset_cells)
            # For each child_cell contained within cell:
            # Compute the set remaining_annotations(level+1, child_cell)
            # of annotations within remaining_annotations(level, cell) - emitted(level, cell)
            # that intersect child_cell.

            # So we need to figure out which child cells are contained in this cell
            
            indices_annotations_this_cell = range(len(annotations_this_cell))
            leftover_annotation_indices = set(indices_annotations_this_cell)-set(subset_indices)
            leftover_annotations = np.take(annotations_this_cell,list(leftover_annotation_indices),axis=0)


            print(f"have {len(leftover_annotations)} annotations leftover")
        
        if level+1 not in remaining_annotations.keys():
            remaining_annotations[level+1] = {}
        print("Looping over child cells: ", child_cells)
        n_annotations_in_child_cells = 0
        for child_cell in child_cells:
            if N_annotations_this_cell == 0:
                remaining_annotations[level+1][child_cell] = np.array([])
                continue
            print(child_cell)
            # figure out which of the leftover annotations fall within this child cell
            # To do that I need to know the bounds of this child chunk
            # To know that I need to know the chunk size and the child chunk
            child_cell_indices = [int(x) for x in child_cell.split('_')]
            child_lower_bounds = [a*b for a,b in zip(child_cell_indices,next_chunk_size)]
            child_upper_bounds = [a+b for a,b, in zip(child_lower_bounds,next_chunk_size)]
#             print(f"Child cell: {child_cell}")
            print("Child lower and upper bounds")
            print(child_lower_bounds)
            print(child_upper_bounds)
         
            # Now use the bounds to find which annotations fall within these bounds
            intersecting_annotations_this_child = find_intersecting_coordinates(
                leftover_annotations,child_lower_bounds,child_upper_bounds)
            print(f"Have {len(intersecting_annotations_this_child)} in this child cell")
            remaining_annotations[level+1][child_cell] = intersecting_annotations_this_child
#             print()
            n_annotations_in_child_cells+=len(intersecting_annotations_this_child)
        if N_annotations_this_cell == 0:
            continue
        print(len(leftover_annotations),n_annotations_in_child_cells)
        print()
        #         assert len(leftover_annotations) == n_annotations_in_child_cells
    level+=1
        # of annotations within remaining_annotations(level=0,cell=0) - emitted(level=0,cell=0)
        # that intersect child_cell. Since there are 4 child cells:
        # and the current level is level0, 
        # remaining_annotations(level=0,cell=0) is all cells and emitted(level=0,cell=0) is the 0.7% that were saved out to spatial0/0_0_0. So of the 99.3% of the cells, figure out which of those intersect with each child cell.

##############
Level: 0
##############
chunk_size=[2160.0, 2560.0, 687.0], maxCount = 1388798
Have these cells: ['0_0_0']
In cell:  0_0_0
started with 1388798 annotations
annotations this cell: [[ 799 1569  387]
 [1150  899  531]
 [1457 1374  424]
 [1081  954  129]
 [1467 1569   73]
 [ 591 1803  309]
 [ 841  974  438]
 [ 863 2415  536]
 [ 826 1183  134]
 [ 493 1267  281]]
subset indices: [ 676004  190017  386842  182828  703775 1364584 1270336 1361066   24294
  632386]
subsetted 10000 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial0/0_0_0
have 1378798 annotations leftover
Looping over child cells:  ['0_0_0', '0_1_0', '1_0_0', '1_1_0']
0_0_0
Child lower and upper bounds
[0.0, 0.0, 0.0]
[1080.0, 1280.0, 687.0]
Have 442341 in this child cell
0_1_0
Child lower and upper bounds
[0.0, 1280.0, 0.0]
[1080.0, 2560.0, 687.0]
Have 390594 in this child cell
1_0_0
Child lower and upper bounds
[1080.0, 0.0, 0.0]
[2160.0, 1280.0, 687.0]
Have 277698 in 

annotations this cell: [[ 841  974  438]
 [ 826 1183  134]
 [ 925  990  353]
 [ 833  984  556]
 [ 694 1220  128]
 [ 678 1068  587]
 [ 713  879  373]
 [ 864 1211   36]
 [1040  906  526]
 [ 890 1248  229]]
subset indices: [ 30474  90503 116758 104298  45891 220685 235754  32401 115665 131907]
subsetted 10000 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial2/1_1_0
have 275265 annotations leftover
Looping over child cells:  ['2_2_0', '2_2_1', '2_3_0', '2_3_1', '3_2_0', '3_2_1', '3_3_0', '3_3_1']
2_2_0
Child lower and upper bounds
[540.0, 640.0, 0.0]
[810.0, 960.0, 343.5]
Have 27920 in this child cell
2_2_1
Child lower and upper bounds
[540.0, 640.0, 343.5]
[810.0, 960.0, 687.0]
Have 23635 in this child cell
2_3_0
Child lower and upper bounds
[540.0, 960.0, 0.0]
[810.0, 1280.0, 343.5]
Have 49592 in this child cell
2_3_1
Child lower and upper bounds
[540.0, 960.0, 343.5]
[810.0, 1280.0, 687.0]
Have 39542 in this child cell
3_2_0
Child lower and

annotations this cell: [[384 878 271]
 [503 897 266]
 [441 721 274]
 [484 830 331]
 [481 821 162]
 [410 731 286]
 [395 950 194]
 [465 867 225]
 [506 824 199]
 [368 866 329]]
subset indices: [ 8238 16024  8032 16843 16028 10215 11006 14754  8563  9908]
subsetted 3671 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial3/1_2_0
have 14535 annotations leftover
Looping over child cells:  ['2_4_0', '2_4_1', '2_5_0', '2_5_1', '3_4_0', '3_4_1', '3_5_0', '3_5_1']
2_4_0
Child lower and upper bounds
[270.0, 640.0, 0.0]
[405.0, 800.0, 171.75]
Have 0 in this child cell
2_4_1
Child lower and upper bounds
[270.0, 640.0, 171.75]
[405.0, 800.0, 343.5]
Have 550 in this child cell
2_5_0
Child lower and upper bounds
[270.0, 800.0, 0.0]
[405.0, 960.0, 171.75]
Have 21 in this child cell
2_5_1
Child lower and upper bounds
[270.0, 800.0, 171.75]
[405.0, 960.0, 343.5]
Have 3754 in this child cell
3_4_0
Child lower and upper bounds
[405.0, 640.0, 0.0]
[540.0, 800.0, 1

Child lower and upper bounds
[270.0, 2080.0, 343.5]
[405.0, 2240.0, 515.25]
Have 0 in this child cell
2_13_3
Child lower and upper bounds
[270.0, 2080.0, 515.25]
[405.0, 2240.0, 687.0]
Have 0 in this child cell
3_12_2
Child lower and upper bounds
[405.0, 1920.0, 343.5]
[540.0, 2080.0, 515.25]
Have 1740 in this child cell
3_12_3
Child lower and upper bounds
[405.0, 1920.0, 515.25]
[540.0, 2080.0, 687.0]
Have 32 in this child cell
3_13_2
Child lower and upper bounds
[405.0, 2080.0, 343.5]
[540.0, 2240.0, 515.25]
Have 274 in this child cell
3_13_3
Child lower and upper bounds
[405.0, 2080.0, 515.25]
[540.0, 2240.0, 687.0]
Have 0 in this child cell
2316 2316

In cell:  1_7_0
started with 0 annotations
Looping over child cells:  ['2_14_0', '2_14_1', '2_15_0', '2_15_1', '3_14_0', '3_14_1', '3_15_0', '3_15_1']
In cell:  1_7_1
started with 4 annotations
annotations this cell: [[ 517 2522  482]
 [ 539 2518  489]
 [ 530 2521  485]
 [ 535 2519  490]]
subset indices: [0]
subsetted 1 annotations
wr

have 39592 annotations leftover
Looping over child cells:  ['4_6_0', '4_6_1', '4_7_0', '4_7_1', '5_6_0', '5_6_1', '5_7_0', '5_7_1']
4_6_0
Child lower and upper bounds
[540.0, 960.0, 0.0]
[675.0, 1120.0, 171.75]
Have 4819 in this child cell
4_6_1
Child lower and upper bounds
[540.0, 960.0, 171.75]
[675.0, 1120.0, 343.5]
Have 4926 in this child cell
4_7_0
Child lower and upper bounds
[540.0, 1120.0, 0.0]
[675.0, 1280.0, 171.75]
Have 5069 in this child cell
4_7_1
Child lower and upper bounds
[540.0, 1120.0, 171.75]
[675.0, 1280.0, 343.5]
Have 5014 in this child cell
5_6_0
Child lower and upper bounds
[675.0, 960.0, 0.0]
[810.0, 1120.0, 171.75]
Have 4981 in this child cell
5_6_1
Child lower and upper bounds
[675.0, 960.0, 171.75]
[810.0, 1120.0, 343.5]
Have 5244 in this child cell
5_7_0
Child lower and upper bounds
[675.0, 1120.0, 0.0]
[810.0, 1280.0, 171.75]
Have 5403 in this child cell
5_7_1
Child lower and upper bounds
[675.0, 1120.0, 171.75]
[810.0, 1280.0, 343.5]
Have 4136 in this chi

annotations this cell: [[ 899  774  173]
 [ 962  641  317]
 [ 933  754   94]
 [1018  782  166]
 [ 846  852  170]
 [ 920  762  118]
 [ 897  810   71]
 [ 817  922  339]
 [ 827  873   96]
 [ 946  883  151]]
subset indices: [ 7669 18556  6037 11913  7486  6176  7373  3444  9176 24881]
subsetted 6122 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial3/3_2_0
have 24237 annotations leftover
Looping over child cells:  ['6_4_0', '6_4_1', '6_5_0', '6_5_1', '7_4_0', '7_4_1', '7_5_0', '7_5_1']
6_4_0
Child lower and upper bounds
[810.0, 640.0, 0.0]
[945.0, 800.0, 171.75]
Have 1399 in this child cell
6_4_1
Child lower and upper bounds
[810.0, 640.0, 171.75]
[945.0, 800.0, 343.5]
Have 3985 in this child cell
6_5_0
Child lower and upper bounds
[810.0, 800.0, 0.0]
[945.0, 960.0, 171.75]
Have 2688 in this child cell
6_5_1
Child lower and upper bounds
[810.0, 800.0, 171.75]
[945.0, 960.0, 343.5]
Have 3847 in this child cell
7_4_0
Child lower and upper bounds


wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial3/4_2_0
have 17832 annotations leftover
Looping over child cells:  ['8_4_0', '8_4_1', '8_5_0', '8_5_1', '9_4_0', '9_4_1', '9_5_0', '9_5_1']
8_4_0
Child lower and upper bounds
[1080.0, 640.0, 0.0]
[1215.0, 800.0, 171.75]
Have 811 in this child cell
8_4_1
Child lower and upper bounds
[1080.0, 640.0, 171.75]
[1215.0, 800.0, 343.5]
Have 3487 in this child cell
8_5_0
Child lower and upper bounds
[1080.0, 800.0, 0.0]
[1215.0, 960.0, 171.75]
Have 2580 in this child cell
8_5_1
Child lower and upper bounds
[1080.0, 800.0, 171.75]
[1215.0, 960.0, 343.5]
Have 3277 in this child cell
9_4_0
Child lower and upper bounds
[1215.0, 640.0, 0.0]
[1350.0, 800.0, 171.75]
Have 728 in this child cell
9_4_1
Child lower and upper bounds
[1215.0, 640.0, 171.75]
[1350.0, 800.0, 343.5]
Have 1767 in this child cell
9_5_0
Child lower and upper bounds
[1215.0, 800.0, 0.0]
[1350.0, 960.0, 171.75]
Have 1845 in this child cell
9_5_1
Chi

Have 2378 in this child cell
9_11_0
Child lower and upper bounds
[1215.0, 1760.0, 0.0]
[1350.0, 1920.0, 171.75]
Have 1848 in this child cell
9_11_1
Child lower and upper bounds
[1215.0, 1760.0, 171.75]
[1350.0, 1920.0, 343.5]
Have 1435 in this child cell
18041 18041

In cell:  4_5_1
started with 11199 annotations
annotations this cell: [[1256 1764  567]
 [1253 1640  456]
 [1098 1892  430]
 [1269 1793  499]
 [1217 1610  405]
 [1285 1610  389]
 [1093 1687  418]
 [1196 1791  582]
 [1114 1647  430]
 [1327 1650  511]]
subset indices: [10509  4541  6504  6282  8206  7994  2685  2478  2122  3381]
subsetted 2258 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial3/4_5_1
have 8941 annotations leftover
Looping over child cells:  ['8_10_2', '8_10_3', '8_11_2', '8_11_3', '9_10_2', '9_10_3', '9_11_2', '9_11_3']
8_10_2
Child lower and upper bounds
[1080.0, 1600.0, 343.5]
[1215.0, 1760.0, 515.25]
Have 1262 in this child cell
8_10_3
Child lower and upper bo

Have 105 in this child cell
11_5_2
Child lower and upper bounds
[1485.0, 800.0, 343.5]
[1620.0, 960.0, 515.25]
Have 2972 in this child cell
11_5_3
Child lower and upper bounds
[1485.0, 800.0, 515.25]
[1620.0, 960.0, 687.0]
Have 1003 in this child cell
12121 12121

In cell:  5_3_0
started with 33095 annotations
annotations this cell: [[1421  996  310]
 [1356 1049  198]
 [1502  979   92]
 [1581 1001  138]
 [1463  990   78]
 [1403  983  200]
 [1596 1035  290]
 [1371 1169   47]
 [1552  988  246]
 [1367  992  124]]
subset indices: [16766 23630 12979 25496 17476 28719 26477 19755   492 22545]
subsetted 6673 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial3/5_3_0
have 26422 annotations leftover
Looping over child cells:  ['10_6_0', '10_6_1', '10_7_0', '10_7_1', '11_6_0', '11_6_1', '11_7_0', '11_7_1']
10_6_0
Child lower and upper bounds
[1350.0, 960.0, 0.0]
[1485.0, 1120.0, 171.75]
Have 3280 in this child cell
10_6_1
Child lower and upper bounds


annotations this cell: [[1685 2022  442]
 [1687 1961  349]
 [1691 2000  435]
 [1680 1997  406]
 [1631 2009  432]
 [1682 2094  359]
 [1762 1970  445]
 [1675 2013  469]
 [1698 1956  344]
 [1656 2037  382]]
subset indices: [ 666 1562 1021 1472    0  578   29  110 1030 1557]
subsetted 420 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial3/6_6_1
have 1662 annotations leftover
Looping over child cells:  ['12_12_2', '12_12_3', '12_13_2', '12_13_3', '13_12_2', '13_12_3', '13_13_2', '13_13_3']
12_12_2
Child lower and upper bounds
[1620.0, 1920.0, 343.5]
[1755.0, 2080.0, 515.25]
Have 1298 in this child cell
12_12_3
Child lower and upper bounds
[1620.0, 1920.0, 515.25]
[1755.0, 2080.0, 687.0]
Have 5 in this child cell
12_13_2
Child lower and upper bounds
[1620.0, 2080.0, 343.5]
[1755.0, 2240.0, 515.25]
Have 131 in this child cell
12_13_3
Child lower and upper bounds
[1620.0, 2080.0, 515.25]
[1755.0, 2240.0, 687.0]
Have 0 in this child cell
13_12_2
Ch

annotations this cell: [[ 267 1448  170]]
subset indices: [0]
subsetted 1 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/1_9_0
have 0 annotations leftover
Looping over child cells:  ['2_18_0', '2_18_1', '2_19_0', '2_19_1', '3_18_0', '3_18_1', '3_19_0', '3_19_1']
2_18_0
Child lower and upper bounds
[135.0, 1440.0, 0.0]
[202.5, 1520.0, 85.875]
Have 0 in this child cell
2_18_1
Child lower and upper bounds
[135.0, 1440.0, 85.875]
[202.5, 1520.0, 171.75]
Have 0 in this child cell
2_19_0
Child lower and upper bounds
[135.0, 1520.0, 0.0]
[202.5, 1600.0, 85.875]
Have 0 in this child cell
2_19_1
Child lower and upper bounds
[135.0, 1520.0, 85.875]
[202.5, 1600.0, 171.75]
Have 0 in this child cell
3_18_0
Child lower and upper bounds
[202.5, 1440.0, 0.0]
[270.0, 1520.0, 85.875]
Have 0 in this child cell
3_18_1
Child lower and upper bounds
[202.5, 1440.0, 85.875]
[270.0, 1520.0, 171.75]
Have 0 in this child cell
3_19_0
Child lower and upper bounds

annotations this cell: [[ 293 1273  208]
 [ 360 1129  199]
 [ 392 1127  267]
 [ 277 1152  207]
 [ 353 1124  286]
 [ 324 1181  293]
 [ 329 1169  261]
 [ 402 1200  252]
 [ 376 1219  309]
 [ 284 1255  179]]
subset indices: [2533 3113 5137 6749 6445 1571 5099 2166 3274 1887]
subsetted 7043 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/2_7_1
have 0 annotations leftover
Looping over child cells:  ['4_14_2', '4_14_3', '4_15_2', '4_15_3', '5_14_2', '5_14_3', '5_15_2', '5_15_3']
4_14_2
Child lower and upper bounds
[270.0, 1120.0, 171.75]
[337.5, 1200.0, 257.625]
Have 0 in this child cell
4_14_3
Child lower and upper bounds
[270.0, 1120.0, 257.625]
[337.5, 1200.0, 343.5]
Have 0 in this child cell
4_15_2
Child lower and upper bounds
[270.0, 1200.0, 171.75]
[337.5, 1280.0, 257.625]
Have 0 in this child cell
4_15_3
Child lower and upper bounds
[270.0, 1200.0, 257.625]
[337.5, 1280.0, 343.5]
Have 0 in this child cell
5_14_2
Child lower and upper bo

Have 0 in this child cell
5_24_5
Child lower and upper bounds
[337.5, 1920.0, 429.375]
[405.0, 2000.0, 515.25]
Have 0 in this child cell
5_25_4
Child lower and upper bounds
[337.5, 2000.0, 343.5]
[405.0, 2080.0, 429.375]
Have 0 in this child cell
5_25_5
Child lower and upper bounds
[337.5, 2000.0, 429.375]
[405.0, 2080.0, 515.25]
Have 0 in this child cell
0 0

In cell:  2_12_3
started with 1 annotations
annotations this cell: [[ 382 2066  627]]
subset indices: [0]
subsetted 1 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/2_12_3
have 0 annotations leftover
Looping over child cells:  ['4_24_6', '4_24_7', '4_25_6', '4_25_7', '5_24_6', '5_24_7', '5_25_6', '5_25_7']
4_24_6
Child lower and upper bounds
[270.0, 1920.0, 515.25]
[337.5, 2000.0, 601.125]
Have 0 in this child cell
4_24_7
Child lower and upper bounds
[270.0, 1920.0, 601.125]
[337.5, 2000.0, 687.0]
Have 0 in this child cell
4_25_6
Child lower and upper bounds
[270.0, 2000.0, 515.2

subset indices: [1586 2254 3115 1784 2221  697 1328 1679  203 3626]
subsetted 3734 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/3_8_0
have 0 annotations leftover
Looping over child cells:  ['6_16_0', '6_16_1', '6_17_0', '6_17_1', '7_16_0', '7_16_1', '7_17_0', '7_17_1']
6_16_0
Child lower and upper bounds
[405.0, 1280.0, 0.0]
[472.5, 1360.0, 85.875]
Have 0 in this child cell
6_16_1
Child lower and upper bounds
[405.0, 1280.0, 85.875]
[472.5, 1360.0, 171.75]
Have 0 in this child cell
6_17_0
Child lower and upper bounds
[405.0, 1360.0, 0.0]
[472.5, 1440.0, 85.875]
Have 0 in this child cell
6_17_1
Child lower and upper bounds
[405.0, 1360.0, 85.875]
[472.5, 1440.0, 171.75]
Have 0 in this child cell
7_16_0
Child lower and upper bounds
[472.5, 1280.0, 0.0]
[540.0, 1360.0, 85.875]
Have 0 in this child cell
7_16_1
Child lower and upper bounds
[472.5, 1280.0, 85.875]
[540.0, 1360.0, 171.75]
Have 0 in this child cell
7_17_0
Child lower and upp

[472.5, 1840.0, 257.625]
[540.0, 1920.0, 343.5]
Have 0 in this child cell
0 0

In cell:  3_11_2
started with 2790 annotations
annotations this cell: [[ 500 1834  359]
 [ 462 1792  370]
 [ 416 1920  385]
 [ 450 1794  401]
 [ 494 1887  360]
 [ 412 1860  373]
 [ 415 1811  384]
 [ 484 1868  357]
 [ 521 1778  399]
 [ 462 1912  417]]
subset indices: [ 505 2525 1722  246 2705 2385 2031  524 1444  293]
subsetted 2790 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/3_11_2
have 0 annotations leftover
Looping over child cells:  ['6_22_4', '6_22_5', '6_23_4', '6_23_5', '7_22_4', '7_22_5', '7_23_4', '7_23_5']
6_22_4
Child lower and upper bounds
[405.0, 1760.0, 343.5]
[472.5, 1840.0, 429.375]
Have 0 in this child cell
6_22_5
Child lower and upper bounds
[405.0, 1760.0, 429.375]
[472.5, 1840.0, 515.25]
Have 0 in this child cell
6_23_4
Child lower and upper bounds
[405.0, 1840.0, 343.5]
[472.5, 1920.0, 429.375]
Have 0 in this child cell
6_23_5
Child lo

[607.5, 560.0, 515.25]
Have 0 in this child cell
8_7_4
Child lower and upper bounds
[540.0, 560.0, 343.5]
[607.5, 640.0, 429.375]
Have 0 in this child cell
8_7_5
Child lower and upper bounds
[540.0, 560.0, 429.375]
[607.5, 640.0, 515.25]
Have 0 in this child cell
9_6_4
Child lower and upper bounds
[607.5, 480.0, 343.5]
[675.0, 560.0, 429.375]
Have 0 in this child cell
9_6_5
Child lower and upper bounds
[607.5, 480.0, 429.375]
[675.0, 560.0, 515.25]
Have 0 in this child cell
9_7_4
Child lower and upper bounds
[607.5, 560.0, 343.5]
[675.0, 640.0, 429.375]
Have 0 in this child cell
9_7_5
Child lower and upper bounds
[607.5, 560.0, 429.375]
[675.0, 640.0, 515.25]
Have 0 in this child cell
0 0

In cell:  4_3_3
started with 0 annotations
Looping over child cells:  ['8_6_6', '8_6_7', '8_7_6', '8_7_7', '9_6_6', '9_6_7', '9_7_6', '9_7_7']
In cell:  4_4_0
started with 1169 annotations
annotations this cell: [[671 748 168]
 [603 792 135]
 [607 678 142]
 [581 751 151]
 [561 759 133]
 [644 732 159]

9_12_2
Child lower and upper bounds
[607.5, 960.0, 171.75]
[675.0, 1040.0, 257.625]
Have 0 in this child cell
9_12_3
Child lower and upper bounds
[607.5, 960.0, 257.625]
[675.0, 1040.0, 343.5]
Have 0 in this child cell
9_13_2
Child lower and upper bounds
[607.5, 1040.0, 171.75]
[675.0, 1120.0, 257.625]
Have 0 in this child cell
9_13_3
Child lower and upper bounds
[607.5, 1040.0, 257.625]
[675.0, 1120.0, 343.5]
Have 0 in this child cell
0 0

In cell:  4_6_2
started with 3989 annotations
annotations this cell: [[ 573 1115  402]
 [ 606  982  491]
 [ 626  970  427]
 [ 620  968  486]
 [ 548 1088  373]
 [ 569  999  441]
 [ 576 1050  439]
 [ 554 1026  346]
 [ 610 1044  382]
 [ 649  981  457]]
subset indices: [2386 2600 3683 1810   19 3855 3426 2256 2950  915]
subsetted 3989 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/4_6_2
have 0 annotations leftover
Looping over child cells:  ['8_12_4', '8_12_5', '8_13_4', '8_13_5', '9_12_4', '9_12_5', '9

[607.5, 1600.0, 257.625]
Have 0 in this child cell
8_19_3
Child lower and upper bounds
[540.0, 1520.0, 257.625]
[607.5, 1600.0, 343.5]
Have 0 in this child cell
9_18_2
Child lower and upper bounds
[607.5, 1440.0, 171.75]
[675.0, 1520.0, 257.625]
Have 0 in this child cell
9_18_3
Child lower and upper bounds
[607.5, 1440.0, 257.625]
[675.0, 1520.0, 343.5]
Have 0 in this child cell
9_19_2
Child lower and upper bounds
[607.5, 1520.0, 171.75]
[675.0, 1600.0, 257.625]
Have 0 in this child cell
9_19_3
Child lower and upper bounds
[607.5, 1520.0, 257.625]
[675.0, 1600.0, 343.5]
Have 0 in this child cell
0 0

In cell:  4_9_2
started with 4888 annotations
annotations this cell: [[ 568 1556  366]
 [ 629 1462  424]
 [ 660 1475  410]
 [ 607 1593  447]
 [ 647 1518  463]
 [ 628 1595  360]
 [ 643 1481  454]
 [ 542 1478  412]
 [ 650 1522  393]
 [ 647 1557  358]]
subset indices: [ 782 3368 1529 2434 4805 1547 3505 2557 2626 3166]
subsetted 4888 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annot

subset indices: [21  4  8  6 17 20 10  7 18 12]
subsetted 22 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/4_15_3
have 0 annotations leftover
Looping over child cells:  ['8_30_6', '8_30_7', '8_31_6', '8_31_7', '9_30_6', '9_30_7', '9_31_6', '9_31_7']
8_30_6
Child lower and upper bounds
[540.0, 2400.0, 515.25]
[607.5, 2480.0, 601.125]
Have 0 in this child cell
8_30_7
Child lower and upper bounds
[540.0, 2400.0, 601.125]
[607.5, 2480.0, 687.0]
Have 0 in this child cell
8_31_6
Child lower and upper bounds
[540.0, 2480.0, 515.25]
[607.5, 2560.0, 601.125]
Have 0 in this child cell
8_31_7
Child lower and upper bounds
[540.0, 2480.0, 601.125]
[607.5, 2560.0, 687.0]
Have 0 in this child cell
9_30_6
Child lower and upper bounds
[607.5, 2400.0, 515.25]
[675.0, 2480.0, 601.125]
Have 0 in this child cell
9_30_7
Child lower and upper bounds
[607.5, 2400.0, 601.125]
[675.0, 2480.0, 687.0]
Have 0 in this child cell
9_31_6
Child lower and upper bounds

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/5_6_1
have 0 annotations leftover
Looping over child cells:  ['10_12_2', '10_12_3', '10_13_2', '10_13_3', '11_12_2', '11_12_3', '11_13_2', '11_13_3']
10_12_2
Child lower and upper bounds
[675.0, 960.0, 171.75]
[742.5, 1040.0, 257.625]
Have 0 in this child cell
10_12_3
Child lower and upper bounds
[675.0, 960.0, 257.625]
[742.5, 1040.0, 343.5]
Have 0 in this child cell
10_13_2
Child lower and upper bounds
[675.0, 1040.0, 171.75]
[742.5, 1120.0, 257.625]
Have 0 in this child cell
10_13_3
Child lower and upper bounds
[675.0, 1040.0, 257.625]
[742.5, 1120.0, 343.5]
Have 0 in this child cell
11_12_2
Child lower and upper bounds
[742.5, 960.0, 171.75]
[810.0, 1040.0, 257.625]
Have 0 in this child cell
11_12_3
Child lower and upper bounds
[742.5, 960.0, 257.625]
[810.0, 1040.0, 343.5]
Have 0 in this child cell
11_13_2
Child lower and upper bounds
[742.5, 1040.0, 171.75]
[810.0, 1120.0, 257.625]
Have 0 in thi

11_20_1
Child lower and upper bounds
[742.5, 1600.0, 85.875]
[810.0, 1680.0, 171.75]
Have 0 in this child cell
11_21_0
Child lower and upper bounds
[742.5, 1680.0, 0.0]
[810.0, 1760.0, 85.875]
Have 0 in this child cell
11_21_1
Child lower and upper bounds
[742.5, 1680.0, 85.875]
[810.0, 1760.0, 171.75]
Have 0 in this child cell
0 0

In cell:  5_10_1
started with 8138 annotations
annotations this cell: [[ 753 1667  231]
 [ 763 1705  279]
 [ 769 1676  268]
 [ 712 1728  340]
 [ 783 1690  308]
 [ 743 1620  231]
 [ 698 1674  186]
 [ 683 1708  219]
 [ 737 1649  229]
 [ 708 1703  340]]
subset indices: [5472 7322 2900  332 2061 1807 4418 7206 6593 5324]
subsetted 8138 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/5_10_1
have 0 annotations leftover
Looping over child cells:  ['10_20_2', '10_20_3', '10_21_2', '10_21_3', '11_20_2', '11_20_3', '11_21_2', '11_21_3']
10_20_2
Child lower and upper bounds
[675.0, 1600.0, 171.75]
[742.5, 1680.0, 257.6

Have 0 in this child cell
0 0

In cell:  5_15_3
started with 2 annotations
annotations this cell: [[ 712 2418  629]
 [ 701 2475  619]]
subset indices: [0 1]
subsetted 2 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/5_15_3
have 0 annotations leftover
Looping over child cells:  ['10_30_6', '10_30_7', '10_31_6', '10_31_7', '11_30_6', '11_30_7', '11_31_6', '11_31_7']
10_30_6
Child lower and upper bounds
[675.0, 2400.0, 515.25]
[742.5, 2480.0, 601.125]
Have 0 in this child cell
10_30_7
Child lower and upper bounds
[675.0, 2400.0, 601.125]
[742.5, 2480.0, 687.0]
Have 0 in this child cell
10_31_6
Child lower and upper bounds
[675.0, 2480.0, 515.25]
[742.5, 2560.0, 601.125]
Have 0 in this child cell
10_31_7
Child lower and upper bounds
[675.0, 2480.0, 601.125]
[742.5, 2560.0, 687.0]
Have 0 in this child cell
11_30_6
Child lower and upper bounds
[742.5, 2400.0, 515.25]
[810.0, 2480.0, 601.125]
Have 0 in this child cell
11_30_7
Child lower and 

Have 0 in this child cell
12_9_2
Child lower and upper bounds
[810.0, 720.0, 171.75]
[877.5, 800.0, 257.625]
Have 0 in this child cell
12_9_3
Child lower and upper bounds
[810.0, 720.0, 257.625]
[877.5, 800.0, 343.5]
Have 0 in this child cell
13_8_2
Child lower and upper bounds
[877.5, 640.0, 171.75]
[945.0, 720.0, 257.625]
Have 0 in this child cell
13_8_3
Child lower and upper bounds
[877.5, 640.0, 257.625]
[945.0, 720.0, 343.5]
Have 0 in this child cell
13_9_2
Child lower and upper bounds
[877.5, 720.0, 171.75]
[945.0, 800.0, 257.625]
Have 0 in this child cell
13_9_3
Child lower and upper bounds
[877.5, 720.0, 257.625]
[945.0, 800.0, 343.5]
Have 0 in this child cell
0 0

In cell:  6_4_2
started with 3142 annotations
annotations this cell: [[828 710 356]
 [822 728 452]
 [825 744 388]
 [812 797 417]
 [931 734 383]
 [943 786 439]
 [842 719 415]
 [942 784 372]
 [854 700 395]
 [920 757 466]]
subset indices: [2234 2276    4 2457 1723  151  506 2993  828  597]
subsetted 3142 annotations
wro

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/6_7_1
have 0 annotations leftover
Looping over child cells:  ['12_14_2', '12_14_3', '12_15_2', '12_15_3', '13_14_2', '13_14_3', '13_15_2', '13_15_3']
12_14_2
Child lower and upper bounds
[810.0, 1120.0, 171.75]
[877.5, 1200.0, 257.625]
Have 0 in this child cell
12_14_3
Child lower and upper bounds
[810.0, 1120.0, 257.625]
[877.5, 1200.0, 343.5]
Have 0 in this child cell
12_15_2
Child lower and upper bounds
[810.0, 1200.0, 171.75]
[877.5, 1280.0, 257.625]
Have 0 in this child cell
12_15_3
Child lower and upper bounds
[810.0, 1200.0, 257.625]
[877.5, 1280.0, 343.5]
Have 0 in this child cell
13_14_2
Child lower and upper bounds
[877.5, 1120.0, 171.75]
[945.0, 1200.0, 257.625]
Have 0 in this child cell
13_14_3
Child lower and upper bounds
[877.5, 1120.0, 257.625]
[945.0, 1200.0, 343.5]
Have 0 in this child cell
13_15_2
Child lower and upper bounds
[877.5, 1200.0, 171.75]
[945.0, 1280.0, 257.625]
Have 0 in

[877.5, 1840.0, 515.25]
Have 0 in this child cell
12_23_4
Child lower and upper bounds
[810.0, 1840.0, 343.5]
[877.5, 1920.0, 429.375]
Have 0 in this child cell
12_23_5
Child lower and upper bounds
[810.0, 1840.0, 429.375]
[877.5, 1920.0, 515.25]
Have 0 in this child cell
13_22_4
Child lower and upper bounds
[877.5, 1760.0, 343.5]
[945.0, 1840.0, 429.375]
Have 0 in this child cell
13_22_5
Child lower and upper bounds
[877.5, 1760.0, 429.375]
[945.0, 1840.0, 515.25]
Have 0 in this child cell
13_23_4
Child lower and upper bounds
[877.5, 1840.0, 343.5]
[945.0, 1920.0, 429.375]
Have 0 in this child cell
13_23_5
Child lower and upper bounds
[877.5, 1840.0, 429.375]
[945.0, 1920.0, 515.25]
Have 0 in this child cell
0 0

In cell:  6_11_3
started with 1019 annotations
annotations this cell: [[ 923 1806  577]
 [ 926 1804  566]
 [ 856 1798  535]
 [ 933 1833  530]
 [ 901 1901  583]
 [ 867 1799  547]
 [ 874 1913  579]
 [ 896 1822  546]
 [ 842 1814  545]
 [ 909 1863  548]]
subset indices: [981 940 

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/7_3_1
have 0 annotations leftover
Looping over child cells:  ['14_6_2', '14_6_3', '14_7_2', '14_7_3', '15_6_2', '15_6_3', '15_7_2', '15_7_3']
14_6_2
Child lower and upper bounds
[945.0, 480.0, 171.75]
[1012.5, 560.0, 257.625]
Have 0 in this child cell
14_6_3
Child lower and upper bounds
[945.0, 480.0, 257.625]
[1012.5, 560.0, 343.5]
Have 0 in this child cell
14_7_2
Child lower and upper bounds
[945.0, 560.0, 171.75]
[1012.5, 640.0, 257.625]
Have 0 in this child cell
14_7_3
Child lower and upper bounds
[945.0, 560.0, 257.625]
[1012.5, 640.0, 343.5]
Have 0 in this child cell
15_6_2
Child lower and upper bounds
[1012.5, 480.0, 171.75]
[1080.0, 560.0, 257.625]
Have 0 in this child cell
15_6_3
Child lower and upper bounds
[1012.5, 480.0, 257.625]
[1080.0, 560.0, 343.5]
Have 0 in this child cell
15_7_2
Child lower and upper bounds
[1012.5, 560.0, 171.75]
[1080.0, 640.0, 257.625]
Have 0 in this child cell
15

annotations this cell: [[ 981  827  409]
 [ 954  904  383]
 [1043  891  490]
 [1069  903  478]
 [1068  855  469]
 [ 995  893  422]
 [ 995  941  436]
 [ 959  891  436]
 [1012  862  514]
 [1073  934  381]]
subset indices: [2965 2159  474 3406 3660 1994 2077 1571 3097 1726]
subsetted 4612 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/7_5_2
have 0 annotations leftover
Looping over child cells:  ['14_10_4', '14_10_5', '14_11_4', '14_11_5', '15_10_4', '15_10_5', '15_11_4', '15_11_5']
14_10_4
Child lower and upper bounds
[945.0, 800.0, 343.5]
[1012.5, 880.0, 429.375]
Have 0 in this child cell
14_10_5
Child lower and upper bounds
[945.0, 800.0, 429.375]
[1012.5, 880.0, 515.25]
Have 0 in this child cell
14_11_4
Child lower and upper bounds
[945.0, 880.0, 343.5]
[1012.5, 960.0, 429.375]
Have 0 in this child cell
14_11_5
Child lower and upper bounds
[945.0, 880.0, 429.375]
[1012.5, 960.0, 515.25]
Have 0 in this child cell
15_10_4
Child lower and

have 0 annotations leftover
Looping over child cells:  ['14_16_0', '14_16_1', '14_17_0', '14_17_1', '15_16_0', '15_16_1', '15_17_0', '15_17_1']
14_16_0
Child lower and upper bounds
[945.0, 1280.0, 0.0]
[1012.5, 1360.0, 85.875]
Have 0 in this child cell
14_16_1
Child lower and upper bounds
[945.0, 1280.0, 85.875]
[1012.5, 1360.0, 171.75]
Have 0 in this child cell
14_17_0
Child lower and upper bounds
[945.0, 1360.0, 0.0]
[1012.5, 1440.0, 85.875]
Have 0 in this child cell
14_17_1
Child lower and upper bounds
[945.0, 1360.0, 85.875]
[1012.5, 1440.0, 171.75]
Have 0 in this child cell
15_16_0
Child lower and upper bounds
[1012.5, 1280.0, 0.0]
[1080.0, 1360.0, 85.875]
Have 0 in this child cell
15_16_1
Child lower and upper bounds
[1012.5, 1280.0, 85.875]
[1080.0, 1360.0, 171.75]
Have 0 in this child cell
15_17_0
Child lower and upper bounds
[1012.5, 1360.0, 0.0]
[1080.0, 1440.0, 85.875]
Have 0 in this child cell
15_17_1
Child lower and upper bounds
[1012.5, 1360.0, 85.875]
[1080.0, 1440.0, 17

have 0 annotations leftover
Looping over child cells:  ['14_26_2', '14_26_3', '14_27_2', '14_27_3', '15_26_2', '15_26_3', '15_27_2', '15_27_3']
14_26_2
Child lower and upper bounds
[945.0, 2080.0, 171.75]
[1012.5, 2160.0, 257.625]
Have 0 in this child cell
14_26_3
Child lower and upper bounds
[945.0, 2080.0, 257.625]
[1012.5, 2160.0, 343.5]
Have 0 in this child cell
14_27_2
Child lower and upper bounds
[945.0, 2160.0, 171.75]
[1012.5, 2240.0, 257.625]
Have 0 in this child cell
14_27_3
Child lower and upper bounds
[945.0, 2160.0, 257.625]
[1012.5, 2240.0, 343.5]
Have 0 in this child cell
15_26_2
Child lower and upper bounds
[1012.5, 2080.0, 171.75]
[1080.0, 2160.0, 257.625]
Have 0 in this child cell
15_26_3
Child lower and upper bounds
[1012.5, 2080.0, 257.625]
[1080.0, 2160.0, 343.5]
Have 0 in this child cell
15_27_2
Child lower and upper bounds
[1012.5, 2160.0, 171.75]
[1080.0, 2240.0, 257.625]
Have 0 in this child cell
15_27_3
Child lower and upper bounds
[1012.5, 2160.0, 257.625]
[1

have 0 annotations leftover
Looping over child cells:  ['16_8_2', '16_8_3', '16_9_2', '16_9_3', '17_8_2', '17_8_3', '17_9_2', '17_9_3']
16_8_2
Child lower and upper bounds
[1080.0, 640.0, 171.75]
[1147.5, 720.0, 257.625]
Have 0 in this child cell
16_8_3
Child lower and upper bounds
[1080.0, 640.0, 257.625]
[1147.5, 720.0, 343.5]
Have 0 in this child cell
16_9_2
Child lower and upper bounds
[1080.0, 720.0, 171.75]
[1147.5, 800.0, 257.625]
Have 0 in this child cell
16_9_3
Child lower and upper bounds
[1080.0, 720.0, 257.625]
[1147.5, 800.0, 343.5]
Have 0 in this child cell
17_8_2
Child lower and upper bounds
[1147.5, 640.0, 171.75]
[1215.0, 720.0, 257.625]
Have 0 in this child cell
17_8_3
Child lower and upper bounds
[1147.5, 640.0, 257.625]
[1215.0, 720.0, 343.5]
Have 0 in this child cell
17_9_2
Child lower and upper bounds
[1147.5, 720.0, 171.75]
[1215.0, 800.0, 257.625]
Have 0 in this child cell
17_9_3
Child lower and upper bounds
[1147.5, 720.0, 257.625]
[1215.0, 800.0, 343.5]
Have 0

Have 0 in this child cell
17_14_3
Child lower and upper bounds
[1147.5, 1120.0, 257.625]
[1215.0, 1200.0, 343.5]
Have 0 in this child cell
17_15_2
Child lower and upper bounds
[1147.5, 1200.0, 171.75]
[1215.0, 1280.0, 257.625]
Have 0 in this child cell
17_15_3
Child lower and upper bounds
[1147.5, 1200.0, 257.625]
[1215.0, 1280.0, 343.5]
Have 0 in this child cell
0 0

In cell:  8_7_2
started with 2540 annotations
annotations this cell: [[1174 1245  372]
 [1111 1255  387]
 [1179 1273  424]
 [1093 1141  452]
 [1135 1216  435]
 [1164 1264  478]
 [1095 1171  475]
 [1147 1192  419]
 [1199 1201  490]
 [1211 1230  448]]
subset indices: [ 682 2398 1692 1366 2056 1406 1949 1252  829 1893]
subsetted 2540 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/8_7_2
have 0 annotations leftover
Looping over child cells:  ['16_14_4', '16_14_5', '16_15_4', '16_15_5', '17_14_4', '17_14_5', '17_15_4', '17_15_5']
16_14_4
Child lower and upper bounds
[1080.0, 11

Child lower and upper bounds
[1080.0, 1920.0, 257.625]
[1147.5, 2000.0, 343.5]
Have 0 in this child cell
16_25_2
Child lower and upper bounds
[1080.0, 2000.0, 171.75]
[1147.5, 2080.0, 257.625]
Have 0 in this child cell
16_25_3
Child lower and upper bounds
[1080.0, 2000.0, 257.625]
[1147.5, 2080.0, 343.5]
Have 0 in this child cell
17_24_2
Child lower and upper bounds
[1147.5, 1920.0, 171.75]
[1215.0, 2000.0, 257.625]
Have 0 in this child cell
17_24_3
Child lower and upper bounds
[1147.5, 1920.0, 257.625]
[1215.0, 2000.0, 343.5]
Have 0 in this child cell
17_25_2
Child lower and upper bounds
[1147.5, 2000.0, 171.75]
[1215.0, 2080.0, 257.625]
Have 0 in this child cell
17_25_3
Child lower and upper bounds
[1147.5, 2000.0, 257.625]
[1215.0, 2080.0, 343.5]
Have 0 in this child cell
0 0

In cell:  8_12_2
started with 1247 annotations
annotations this cell: [[1102 2064  392]
 [1213 2034  429]
 [1175 2009  354]
 [1083 2037  426]
 [1137 2037  352]
 [1086 2006  357]
 [1104 2022  379]
 [1128 1948  

Have 0 in this child cell
18_7_6
Child lower and upper bounds
[1215.0, 560.0, 515.25]
[1282.5, 640.0, 601.125]
Have 0 in this child cell
18_7_7
Child lower and upper bounds
[1215.0, 560.0, 601.125]
[1282.5, 640.0, 687.0]
Have 0 in this child cell
19_6_6
Child lower and upper bounds
[1282.5, 480.0, 515.25]
[1350.0, 560.0, 601.125]
Have 0 in this child cell
19_6_7
Child lower and upper bounds
[1282.5, 480.0, 601.125]
[1350.0, 560.0, 687.0]
Have 0 in this child cell
19_7_6
Child lower and upper bounds
[1282.5, 560.0, 515.25]
[1350.0, 640.0, 601.125]
Have 0 in this child cell
19_7_7
Child lower and upper bounds
[1282.5, 560.0, 601.125]
[1350.0, 640.0, 687.0]
Have 0 in this child cell
0 0

In cell:  9_4_0
started with 728 annotations
annotations this cell: [[1241  776  171]
 [1294  691  160]
 [1254  763  159]
 [1230  796   88]
 [1252  746  144]
 [1264  761  158]
 [1256  745  160]
 [1301  720   85]
 [1293  771   80]
 [1218  743  153]]
subset indices: [381 558 720 158 599 174 392  34  46 648]

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/9_7_0
have 0 annotations leftover
Looping over child cells:  ['18_14_0', '18_14_1', '18_15_0', '18_15_1', '19_14_0', '19_14_1', '19_15_0', '19_15_1']
18_14_0
Child lower and upper bounds
[1215.0, 1120.0, 0.0]
[1282.5, 1200.0, 85.875]
Have 0 in this child cell
18_14_1
Child lower and upper bounds
[1215.0, 1120.0, 85.875]
[1282.5, 1200.0, 171.75]
Have 0 in this child cell
18_15_0
Child lower and upper bounds
[1215.0, 1200.0, 0.0]
[1282.5, 1280.0, 85.875]
Have 0 in this child cell
18_15_1
Child lower and upper bounds
[1215.0, 1200.0, 85.875]
[1282.5, 1280.0, 171.75]
Have 0 in this child cell
19_14_0
Child lower and upper bounds
[1282.5, 1120.0, 0.0]
[1350.0, 1200.0, 85.875]
Have 0 in this child cell
19_14_1
Child lower and upper bounds
[1282.5, 1120.0, 85.875]
[1350.0, 1200.0, 171.75]
Have 0 in this child cell
19_15_0
Child lower and upper bounds
[1282.5, 1200.0, 0.0]
[1350.0, 1280.0, 85.875]
Have 0 in t

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/9_12_3
have 0 annotations leftover
Looping over child cells:  ['18_24_6', '18_24_7', '18_25_6', '18_25_7', '19_24_6', '19_24_7', '19_25_6', '19_25_7']
18_24_6
Child lower and upper bounds
[1215.0, 1920.0, 515.25]
[1282.5, 2000.0, 601.125]
Have 0 in this child cell
18_24_7
Child lower and upper bounds
[1215.0, 1920.0, 601.125]
[1282.5, 2000.0, 687.0]
Have 0 in this child cell
18_25_6
Child lower and upper bounds
[1215.0, 2000.0, 515.25]
[1282.5, 2080.0, 601.125]
Have 0 in this child cell
18_25_7
Child lower and upper bounds
[1215.0, 2000.0, 601.125]
[1282.5, 2080.0, 687.0]
Have 0 in this child cell
19_24_6
Child lower and upper bounds
[1282.5, 1920.0, 515.25]
[1350.0, 2000.0, 601.125]
Have 0 in this child cell
19_24_7
Child lower and upper bounds
[1282.5, 1920.0, 601.125]
[1350.0, 2000.0, 687.0]
Have 0 in this child cell
19_25_6
Child lower and upper bounds
[1282.5, 2000.0, 515.25]
[1350.0, 2080.0, 601

20_12_2
Child lower and upper bounds
[1350.0, 960.0, 171.75]
[1417.5, 1040.0, 257.625]
Have 0 in this child cell
20_12_3
Child lower and upper bounds
[1350.0, 960.0, 257.625]
[1417.5, 1040.0, 343.5]
Have 0 in this child cell
20_13_2
Child lower and upper bounds
[1350.0, 1040.0, 171.75]
[1417.5, 1120.0, 257.625]
Have 0 in this child cell
20_13_3
Child lower and upper bounds
[1350.0, 1040.0, 257.625]
[1417.5, 1120.0, 343.5]
Have 0 in this child cell
21_12_2
Child lower and upper bounds
[1417.5, 960.0, 171.75]
[1485.0, 1040.0, 257.625]
Have 0 in this child cell
21_12_3
Child lower and upper bounds
[1417.5, 960.0, 257.625]
[1485.0, 1040.0, 343.5]
Have 0 in this child cell
21_13_2
Child lower and upper bounds
[1417.5, 1040.0, 171.75]
[1485.0, 1120.0, 257.625]
Have 0 in this child cell
21_13_3
Child lower and upper bounds
[1417.5, 1040.0, 257.625]
[1485.0, 1120.0, 343.5]
Have 0 in this child cell
0 0

In cell:  10_6_2
started with 2432 annotations
annotations this cell: [[1421 1084  431]
 [1

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/10_10_0
have 0 annotations leftover
Looping over child cells:  ['20_20_0', '20_20_1', '20_21_0', '20_21_1', '21_20_0', '21_20_1', '21_21_0', '21_21_1']
20_20_0
Child lower and upper bounds
[1350.0, 1600.0, 0.0]
[1417.5, 1680.0, 85.875]
Have 0 in this child cell
20_20_1
Child lower and upper bounds
[1350.0, 1600.0, 85.875]
[1417.5, 1680.0, 171.75]
Have 0 in this child cell
20_21_0
Child lower and upper bounds
[1350.0, 1680.0, 0.0]
[1417.5, 1760.0, 85.875]
Have 0 in this child cell
20_21_1
Child lower and upper bounds
[1350.0, 1680.0, 85.875]
[1417.5, 1760.0, 171.75]
Have 0 in this child cell
21_20_0
Child lower and upper bounds
[1417.5, 1600.0, 0.0]
[1485.0, 1680.0, 85.875]
Have 0 in this child cell
21_20_1
Child lower and upper bounds
[1417.5, 1600.0, 85.875]
[1485.0, 1680.0, 171.75]
Have 0 in this child cell
21_21_0
Child lower and upper bounds
[1417.5, 1680.0, 0.0]
[1485.0, 1760.0, 85.875]
Have 0 in

Have 0 in this child cell
20_26_5
Child lower and upper bounds
[1350.0, 2080.0, 429.375]
[1417.5, 2160.0, 515.25]
Have 0 in this child cell
20_27_4
Child lower and upper bounds
[1350.0, 2160.0, 343.5]
[1417.5, 2240.0, 429.375]
Have 0 in this child cell
20_27_5
Child lower and upper bounds
[1350.0, 2160.0, 429.375]
[1417.5, 2240.0, 515.25]
Have 0 in this child cell
21_26_4
Child lower and upper bounds
[1417.5, 2080.0, 343.5]
[1485.0, 2160.0, 429.375]
Have 0 in this child cell
21_26_5
Child lower and upper bounds
[1417.5, 2080.0, 429.375]
[1485.0, 2160.0, 515.25]
Have 0 in this child cell
21_27_4
Child lower and upper bounds
[1417.5, 2160.0, 343.5]
[1485.0, 2240.0, 429.375]
Have 0 in this child cell
21_27_5
Child lower and upper bounds
[1417.5, 2160.0, 429.375]
[1485.0, 2240.0, 515.25]
Have 0 in this child cell
0 0

In cell:  10_13_3
started with 139 annotations
annotations this cell: [[1449 2142  523]
 [1419 2158  520]
 [1482 2085  519]
 [1472 2119  517]
 [1357 2170  521]
 [1354 2196  5

0 0

In cell:  11_5_3
started with 1003 annotations
annotations this cell: [[1554  934  566]
 [1576  912  568]
 [1513  844  532]
 [1516  855  522]
 [1601  889  552]
 [1579  883  533]
 [1561  931  523]
 [1509  834  518]
 [1524  916  541]
 [1490  846  578]]
subset indices: [766 115 953 685 983  37 531 806 721  58]
subsetted 1003 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/11_5_3
have 0 annotations leftover
Looping over child cells:  ['22_10_6', '22_10_7', '22_11_6', '22_11_7', '23_10_6', '23_10_7', '23_11_6', '23_11_7']
22_10_6
Child lower and upper bounds
[1485.0, 800.0, 515.25]
[1552.5, 880.0, 601.125]
Have 0 in this child cell
22_10_7
Child lower and upper bounds
[1485.0, 800.0, 601.125]
[1552.5, 880.0, 687.0]
Have 0 in this child cell
22_11_6
Child lower and upper bounds
[1485.0, 880.0, 515.25]
[1552.5, 960.0, 601.125]
Have 0 in this child cell
22_11_7
Child lower and upper bounds
[1485.0, 880.0, 601.125]
[1552.5, 960.0, 687.0]
Ha

23_18_5
Child lower and upper bounds
[1552.5, 1440.0, 429.375]
[1620.0, 1520.0, 515.25]
Have 0 in this child cell
23_19_4
Child lower and upper bounds
[1552.5, 1520.0, 343.5]
[1620.0, 1600.0, 429.375]
Have 0 in this child cell
23_19_5
Child lower and upper bounds
[1552.5, 1520.0, 429.375]
[1620.0, 1600.0, 515.25]
Have 0 in this child cell
0 0

In cell:  11_9_3
started with 898 annotations
annotations this cell: [[1500 1544  551]
 [1603 1446  546]
 [1505 1536  523]
 [1503 1543  552]
 [1561 1550  527]
 [1532 1496  554]
 [1509 1573  548]
 [1584 1519  561]
 [1594 1464  597]
 [1598 1585  537]]
subset indices: [ 72 568 241 257 735 559 608 224 886 390]
subsetted 898 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/11_9_3
have 0 annotations leftover
Looping over child cells:  ['22_18_6', '22_18_7', '22_19_6', '22_19_7', '23_18_6', '23_18_7', '23_19_6', '23_19_7']
22_18_6
Child lower and upper bounds
[1485.0, 1440.0, 515.25]
[1552.5, 1520.0, 601.

have 0 annotations leftover
Looping over child cells:  ['24_10_4', '24_10_5', '24_11_4', '24_11_5', '25_10_4', '25_10_5', '25_11_4', '25_11_5']
24_10_4
Child lower and upper bounds
[1620.0, 800.0, 343.5]
[1687.5, 880.0, 429.375]
Have 0 in this child cell
24_10_5
Child lower and upper bounds
[1620.0, 800.0, 429.375]
[1687.5, 880.0, 515.25]
Have 0 in this child cell
24_11_4
Child lower and upper bounds
[1620.0, 880.0, 343.5]
[1687.5, 960.0, 429.375]
Have 0 in this child cell
24_11_5
Child lower and upper bounds
[1620.0, 880.0, 429.375]
[1687.5, 960.0, 515.25]
Have 0 in this child cell
25_10_4
Child lower and upper bounds
[1687.5, 800.0, 343.5]
[1755.0, 880.0, 429.375]
Have 0 in this child cell
25_10_5
Child lower and upper bounds
[1687.5, 800.0, 429.375]
[1755.0, 880.0, 515.25]
Have 0 in this child cell
25_11_4
Child lower and upper bounds
[1687.5, 880.0, 343.5]
[1755.0, 960.0, 429.375]
Have 0 in this child cell
25_11_5
Child lower and upper bounds
[1687.5, 880.0, 429.375]
[1755.0, 960.0

[1755.0, 1840.0, 257.625]
Have 0 in this child cell
25_22_3
Child lower and upper bounds
[1687.5, 1760.0, 257.625]
[1755.0, 1840.0, 343.5]
Have 0 in this child cell
25_23_2
Child lower and upper bounds
[1687.5, 1840.0, 171.75]
[1755.0, 1920.0, 257.625]
Have 0 in this child cell
25_23_3
Child lower and upper bounds
[1687.5, 1840.0, 257.625]
[1755.0, 1920.0, 343.5]
Have 0 in this child cell
0 0

In cell:  12_11_2
started with 1981 annotations
annotations this cell: [[1673 1767  451]
 [1728 1836  443]
 [1643 1814  414]
 [1646 1910  468]
 [1713 1859  384]
 [1679 1916  490]
 [1657 1769  417]
 [1737 1823  360]
 [1651 1835  345]
 [1704 1849  373]]
subset indices: [ 266 1904 1792  666  722  982 1174 1729 1816 1659]
subsetted 1981 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/12_11_2
have 0 annotations leftover
Looping over child cells:  ['24_22_4', '24_22_5', '24_23_4', '24_23_5', '25_22_4', '25_22_5', '25_23_4', '25_23_5']
24_22_4
Child lowe

wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/13_8_1
have 0 annotations leftover
Looping over child cells:  ['26_16_2', '26_16_3', '26_17_2', '26_17_3', '27_16_2', '27_16_3', '27_17_2', '27_17_3']
26_16_2
Child lower and upper bounds
[1755.0, 1280.0, 171.75]
[1822.5, 1360.0, 257.625]
Have 0 in this child cell
26_16_3
Child lower and upper bounds
[1755.0, 1280.0, 257.625]
[1822.5, 1360.0, 343.5]
Have 0 in this child cell
26_17_2
Child lower and upper bounds
[1755.0, 1360.0, 171.75]
[1822.5, 1440.0, 257.625]
Have 0 in this child cell
26_17_3
Child lower and upper bounds
[1755.0, 1360.0, 257.625]
[1822.5, 1440.0, 343.5]
Have 0 in this child cell
27_16_2
Child lower and upper bounds
[1822.5, 1280.0, 171.75]
[1890.0, 1360.0, 257.625]
Have 0 in this child cell
27_16_3
Child lower and upper bounds
[1822.5, 1280.0, 257.625]
[1890.0, 1360.0, 343.5]
Have 0 in this child cell
27_17_2
Child lower and upper bounds
[1822.5, 1360.0, 171.75]
[1890.0, 1440.0, 257

 [1892 1118  385]]
subset indices: [62 49  3 21 36 54 51 40 25 64]
subsetted 66 annotations
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/spatial4/14_6_2
have 0 annotations leftover
Looping over child cells:  ['28_12_4', '28_12_5', '28_13_4', '28_13_5', '29_12_4', '29_12_5', '29_13_4', '29_13_5']
28_12_4
Child lower and upper bounds
[1890.0, 960.0, 343.5]
[1957.5, 1040.0, 429.375]
Have 0 in this child cell
28_12_5
Child lower and upper bounds
[1890.0, 960.0, 429.375]
[1957.5, 1040.0, 515.25]
Have 0 in this child cell
28_13_4
Child lower and upper bounds
[1890.0, 1040.0, 343.5]
[1957.5, 1120.0, 429.375]
Have 0 in this child cell
28_13_5
Child lower and upper bounds
[1890.0, 1040.0, 429.375]
[1957.5, 1120.0, 515.25]
Have 0 in this child cell
29_12_4
Child lower and upper bounds
[1957.5, 960.0, 343.5]
[2025.0, 1040.0, 429.375]
Have 0 in this child cell
29_12_5
Child lower and upper bounds
[1957.5, 960.0, 429.375]
[2025.0, 1040.0, 515.25]
Have 0 in this child

In [301]:
# Use the remaining_annotations dict to make the spatial part of the info file
limit=10000
grid_shape = [1,1,1]
chunk_size = [2160,2560,687]

spatial_array = []
for level in remaining_annotations.keys():
    N_annotations_this_level = [len(x) for x in remaining_annotations[level].values()]
    maxCount[level] = max(N_annotations_this_level)
    if maxCount[level] == 0:
        break
    factor = calculate_factors(level)
    grid_shape = [a*b for a,b in zip(grid_shape,factor)]
    chunk_size = [a/b for a,b in zip(chunk_size,factor)]
    spatial_dict = {"chunk_size":chunk_size,
                    "grid_shape":grid_shape,
                    "key":f"spatial{level}",
                    "limit":limit}
    spatial_array.append(spatial_dict)
spatial_array

[{'chunk_size': [2160.0, 2560.0, 687.0],
  'grid_shape': [1, 1, 1],
  'key': 'spatial0',
  'limit': 10000},
 {'chunk_size': [1080.0, 1280.0, 687.0],
  'grid_shape': [2, 2, 1],
  'key': 'spatial1',
  'limit': 10000},
 {'chunk_size': [540.0, 640.0, 687.0],
  'grid_shape': [4, 4, 1],
  'key': 'spatial2',
  'limit': 10000},
 {'chunk_size': [270.0, 320.0, 343.5],
  'grid_shape': [8, 8, 2],
  'key': 'spatial3',
  'limit': 10000},
 {'chunk_size': [135.0, 160.0, 171.75],
  'grid_shape': [16, 16, 4],
  'key': 'spatial4',
  'limit': 10000}]

In [305]:
info={
  "@type": "neuroglancer_annotations_v1",
  "annotation_type": "POINT",
  "by_id": {
    "key": "by_id"
  },
  "dimensions": {
    "x": [
      "5e-06",
      "m"
    ],
    "y": [
      "5e-06",
      "m"
    ],
    "z": [
      "1e-05",
      "m"
    ]
  },
  "lower_bound": [
    0,
    0,
    0
  ],
  "properties": [
  ],
  "relationships": [],
  "spatial": [{'chunk_size': [2160.0, 2560.0, 687.0],
  'grid_shape': [1, 1, 1],
  'key': 'spatial0',
  'limit': 10000},
 {'chunk_size': [1080.0, 1280.0, 687.0],
  'grid_shape': [2, 2, 1],
  'key': 'spatial1',
  'limit': 10000},
 {'chunk_size': [540.0, 640.0, 687.0],
  'grid_shape': [4, 4, 1],
  'key': 'spatial2',
  'limit': 10000},
 {'chunk_size': [270.0, 320.0, 343.5],
  'grid_shape': [8, 8, 2],
  'key': 'spatial3',
  'limit': 10000},
 {'chunk_size': [135.0, 160.0, 171.75],
  'grid_shape': [16, 16, 4],
  'key': 'spatial4',
  'limit': 10000}],
  "upper_bound": [
    2160,
    2560,
    687
  ]
}

In [306]:
info_filename = '/home/ahoag/ngdemo/demo_bucket/test_annotations/test_multispatialindex/info'
with open(info_filename,'w') as outfile:
    json.dump(info,outfile,indent=2)

## Compare to a single spatial index for performance testing

In [270]:
# We already know how to encode just the coordinates. Do it like so for the first 100 points
filename = '/home/ahoag/ngdemo/demo_bucket/test_annotations/an5_singlespatial/spatial0/0_0_0'
# coordinates = converted_points
total_count = len(unique_coordinates)
print(f"Have {total_count} coordinates")
with open(filename,'wb') as outfile:
    buf = struct.pack('<Q',total_count)
    pt_buf = b''.join(struct.pack('<3f',x,y,z) for (x,y,z) in unique_coordinates)
    buf += pt_buf
    id_buf = struct.pack('<%sQ' % len(unique_coordinates), *range(len(unique_coordinates)))
    buf += id_buf
    outfile.write(buf)
print(f"wrote {filename}")

Have 1388798 coordinates
wrote /home/ahoag/ngdemo/demo_bucket/test_annotations/an5_singlespatial/spatial0/0_0_0


In [266]:
coordinates

array([[1440,  948,  219],
       [1421, 1391,  446],
       [1628,  963,  288],
       ...,
       [ 601, 1388,  454],
       [ 461,  751,  431],
       [ 423, 1242,  391]])

In [268]:
# and the info file needs to look like this:
info = {
  "@type": "neuroglancer_annotations_v1",
  "annotation_type": "POINT",
  "by_id": {
    "key": "by_id"
  },
  "dimensions": {
    "x": [
      "5e-06",
      "m"
    ],
    "y": [
      "5e-06",
      "m"
    ],
    "z": [
      "1e-05",
      "m"
    ]
  },
  "lower_bound": [
    0,
    0,
    0
  ],
  "properties": [],
  "relationships": [],
  "spatial": [
    {
      "chunk_size": [
        2160,
        2560,
        687
      ],
      "grid_shape": [
        1,
        1,
        1
      ],
      "key": "spatial0",
      "limit": 10000
    }
  ],
  "upper_bound": [
    2160,
    2560,
    687
  ]
}

In [269]:
info_filename = '/home/ahoag/ngdemo/demo_bucket/test_annotations/an5_singlespatial/info'
with open(info_filename,'w') as outfile:
    json.dump(info,outfile,indent=2)

The number of annotations in the spatially indexed layer is identical to that in the singly indexed layer but it loads way faster! The algorithm is somewhat complicated and hard to debug, but  